### ISSUE TITLE
No module named 'utils'

### ISSUE THREAD

**Issue by 1171000712** [zhoujiahuan1991/AAAI2025-CAPrompt#1]
Traceback (most recent call last):
  File "/AAAI2025-CAPrompt/main.py", line 17, in <module>
    from datasets import build_continual_dataloader
  File "/AAAI2025-CAPrompt/datasets.py", line 11, in <module>
    import utils
ModuleNotFoundError: No module named 'utils'

**Comment by qiweili00** [comment]
Thanks for pointing that out, we have uploaded utils.py file
